#!/bin/bash

curl -w @- -o /dev/null -H 'Pragma: no-cache' -H 'Cache-Control: no-cache,no-store' -s "$@" <<'EOF'
           dns:  %{time_namelookup}\n
 tcp_handshake:  %{time_connect}\n
 tls_handshake:  %{time_appconnect}\n
   pretransfer:  %{time_pretransfer}\n
  posttransfer:  %{time_pretransfer}\n
      redirect:  %{time_redirect}\n
     first_rcv:  %{time_starttransfer}\n
               ----------\n
         total:  %{time_total}\n
EOF
